#!/bin/bash

# Script Comments
# Author: Dhruv Vishnukumar Patel
# Date: Nov 05th, 2023
# This script generates a system information report.

# Collect system information
USERNAME=$(whoami)
DATETIME=$(date '+%Y-%m-%d %H:%M:%S')
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p | sed 's/up //')

# Gathering Hardware Information
CPU=$(lshw -class processor | grep 'product' | awk -F: '{print $2}' | sed 's/^ //')
CPU_SPEEDS=$(lscpu | grep 'MHz' | awk '{print $3 " MHz"}')
RAM=$(grep MemTotal /proc/meminfo | awk '{print int($2/1024) " MB"}')
DISKS=$(lshw -class disk | grep 'product\|size' | xargs -L2 | sed 's/size: //' | sed 's/product: //')
VIDEO=$(lshw -class display | grep 'product' | awk -F: '{print $2}' | sed 's/^ //')

# Gathering Network Information
FQDN=$(hostname --fqdn)
HOST_ADDRESS=$(ip a show | grep 'inet ' | awk '{print $2}' | head -n 1)
GATEWAY_ADDRESS=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}')

# Gathering Network Interface
INTERFACE=$(ip link | awk -F: '$0 !~ "lo|^[^0-9]"{print $2;getline}')
INTERFACE_MODEL=$(lshw -class network | grep 'description' | awk -F: '{print $2}' | sed 's/^ //')
IP_ADDRESS=$(ip a show $INTERFACE | grep 'inet ' | awk '{print $2}')

# Gathering System Status
USERS_LOGGED_IN=$(who | awk '{print $1}' | sort | uniq | tr '\n' ', ')
DISK_SPACE=$(df -h | awk '$NF=="/"{printf "%s available out of %s\n", $4,$2}')
PROCESS_COUNT=$(ps -e --no-headers | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1", "$2", "$3}')
MEMORY_ALLOCATION=$(free -m | awk 'NR==2{printf "%sMB of %sMB\n", $3,$2}')
LISTENING_PORTS=$(ss -tuln | awk '/LISTEN/{print $5}' | tr '\n' ' ')
UFW_RULES=$(sudo ufw status | grep -v "(v6)" | awk '/ALLOW/{print $1 " " $2 " " $3}' | tr '\n' ' ')

# Generate report in detail
{
echo ""
echo "System Report generated by $USERNAME, $DATETIME"
echo ""
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo ""
echo "Hardware Information"
echo "--------------------"
echo "cpu: $CPU"
echo "Speed: $CPU_SPEEDS"
echo "Ram: $RAM"
echo "Disk(s): $DISKS"
echo "Video: $VIDEO"
echo ""
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_ADDRESS"
echo "Gateway IP: $GATEWAY_ADDRESS"
echo "DNS Server: $DNS_SERVER"
echo ""
echo "InterfaceName: $INTERFACE"
echo "Model: $INTERFACE_MODEL"
echo "IP Address: $IP_ADDRESS"
echo ""
echo "System Status"
echo "-------------"
echo "Users Logged In: $USERS_LOGGED_IN"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Memory Allocation: $MEMORY_ALLOCATION"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Rules: $UFW_RULES"
echo ""
} > Assignment1_report.txt

# Output to console
cat Assignment1_report.txt

# End of the script
